### ISSUE TITLE
[feature request] more depth colors please

### ISSUE THREAD

**Issue by hyperphysin** [james-tindal/obsidian-mindmap-nextgen#214]
4 colors are not enough. Can we get like 6 or 7 colors?

**Comment by james-tindal** [comment]
You can make a [custom stylesheet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets).

```css
g[data-depth="0"] line {
  stroke: magenta
}
```
