### ISSUE TITLE
CSS Customization: How to set different font sizes for different node depths/levels?

### ISSUE THREAD

**Issue by laxisforte** [james-tindal/obsidian-mindmap-nextgen#270]
I'm trying to customize the appearance of my mind maps by setting different font sizes for nodes at different depth levels. I've been trying to achieve this with custom CSS snippets in Obsidian, but so far without success.

**What I'm trying to achieve:**
I want nodes at the root level (or data-depth="1") to have the largest font size, with font sizes decreasing for nodes at deeper levels (e.g., data-depth="2", data-depth="3", etc.).

**What I've observed from Developer Tools:**
When inspecting the SVG structure of the mind map, I can see that each node group (<g class="markmap-node">) has a data-depth="N" attribute (e.g., data-depth="1", data-depth="2", data-depth="3"), which seems perfect for targeting specific levels. The text itself is within a <div> inside a <foreignObject class="markmap-foreign">, which is a child of the g.markmap-node[data-depth="N"] element.

I've also noticed a global CSS variable --markmap-font which is initially set to something like 300 16px / 20px sans-serif.
CSS I've tried (among other variations):
**Attempt 1: Directly styling the div with font-size**

```css
.markmap svg g[data-depth="1"].markmap-node .markmap-foreign div {
  font-size: 22px !important;
}
.markmap svg g[data-depth="2"].markmap-node .markmap-foreign div {
  font-size: 20px !important;
}
/* ... and so on for other depths ... */
```

**Attempt 2: Directly styling the div with the full font property**

```css
.markmap svg g[data-depth="1"].markmap-node .markmap-foreign div {
  font: normal normal normal 22px / normal sans-serif !important;
}
.markmap svg g[data-depth="2"].markmap-node .markmap-foreign div {
  font: normal normal normal 20px / normal sans-serif !important;
}
/* ... and so on for other depths ... */
```
**Attempt 3: Redefining the --markmap-font CSS variable per depth**

```css
.markmap svg g[data-depth="1"].markmap-node {
  --markmap-font: 300 22px / normal sans-serif !important;
}
.markmap svg g[data-depth="2"].markmap-node {
  --markmap-font: 300 20px / normal sans-serif !important;
}
/* ... and so on for other depths ... */

/* Ensuring the variable is applied (though this might be default behavior) */
.markmap svg g.markmap-node .markmap-foreign div {
  font: var(--markmap-font) !important;
}
```
Unfortunately, none of these approaches have resulted in the desired change in font sizes; all nodes still render with the default font size (16px).

Could you please provide guidance on the correct CSS selectors and properties to use to achieve different font sizes for different node depths?

Is there a specific CSS variable structure or a recommended way to override the default font styling per level that I might be missing? Any help or examples would be greatly appreciated!

Environment:
Windows 11
Obsidian version: v1.8.10
Mindmap NextGen v1.13.2
